In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# 행렬분해로 평점데이터(Full matrix) 채우기
import numpy as np

R = np.array([[4, np.NaN, 4, 2, 5],
              [np.NaN, 4, np.NaN, 1, 2],
              [np.NaN, 1, 5, 1, np.NaN],
              [1, 5, np.NaN, np.NaN, 3]])

display(R)

array([[ 4., nan,  4.,  2.,  5.],
       [nan,  4., nan,  1.,  2.],
       [nan,  1.,  5.,  1., nan],
       [ 1.,  5., nan, nan,  3.]])

In [ ]:
def RMSE(answer, prediction):
  e = (np.array(answer) - np.array(prediction)) ** 2
  e = e[~np.isnan(e)]
  return np.sqrt(np.mean((e)))

In [ ]:
# 4, 5
num_users, num_movies = R.shape
K = 3

P = np.random.normal(size=(num_users, K))
Q = np.random.normal(size=(K, num_movies))
display(P)
display(Q)

array([[-1.59592304,  0.26771649, -1.24063343],
       [-0.1481285 , -0.25569508, -0.1928281 ],
       [ 0.7872326 , -1.81440015, -0.26451976],
       [ 2.3022064 , -2.00514091,  1.05090371]])

array([[ 0.6650514 , -1.06267047,  0.69155337,  1.48236298, -0.24505469],
       [-1.52031284,  0.15968626, -0.24497232,  0.01857716, -2.15625628],
       [-0.55239486,  0.00505515,  1.04421933,  1.14365566, -0.80904593]])

In [ ]:
display(np.dot(P, Q))

array([[ 1.50307661, -0.80143072,  1.10437153,  0.53883904,  1.19282275],
       [-0.13348991,  0.42893178,  0.37483519,  2.92075406,  1.19458358],
       [-2.73853758,  1.53427163, -1.06892029, -1.01295757, -0.24632708],
       [-1.16786442,  0.46051409, -0.1750349 , -2.45043959,  0.24354431]])

In [ ]:
def mf_rmse(R, PQ):
  rows, columns = R.shape
  R_non_zeros = []
  PQ_non_zeros = []

  for i in range(rows):
    for j in range(columns):
      if ~(np.isnan(R[i, j])):
        R_non_zeros.append(R[i, j])
        PQ_non_zeros.append(PQ[i, j])

  return RMSE(R_non_zeros, PQ_non_zeros)

print(mf_rmse(R, np.dot(P, Q)))

[ 6.2346264   8.38466426  2.13499136 14.49459859 12.7525282   3.68929615
  0.64869562  0.28544617 36.83179347  4.05199819  4.69963616 20.6069323
  7.59804798]
3.068616010363132


In [ ]:
def RMSE_2d(answer, prediction):
  answer = answer.reshape(-1, 1).squeeze()
  prediction = prediction.reshape(-1, 1).squeeze()
  return RMSE(answer, prediction)

print(RMSE_2d(R, np.dot(P, Q)))

3.068616010363132


In [ ]:
learning_rate = 0.005
r_rate = 0.005

for epoch in range(1000):
  for i in range(num_users):
    for j in range(num_movies):
      # 실제값
      true_r = R[i, j]
      
      if np.isnan(true_r):
        continue
      
      # 예측값
      pred_r = np.dot(P[i, :], Q[:, j])
      error = true_r - pred_r

      P[i, :] = P[i, :] + learning_rate * (error * Q[:, j] - r_rate * P[i, :])
      Q[:, j] = Q[:, j] + learning_rate * (error * P[i, :] - r_rate * Q[:, j])

  if epoch % 10 == 0:
    print(f'RMSE : {epoch}, {RMSE_2d(R, np.dot(P, Q))}')

RMSE : 0, 0.22060720729944377
RMSE : 10, 0.20941634669269102
RMSE : 20, 0.19898260735005904
RMSE : 30, 0.18913406127516294
RMSE : 40, 0.1797519377806569
RMSE : 50, 0.17075588323732102
RMSE : 60, 0.162092953780769
RMSE : 70, 0.15372955330891785
RMSE : 80, 0.14564558014648735
RMSE : 90, 0.13783018445181064
RMSE : 100, 0.13027868574266757
RMSE : 110, 0.12299032503421319
RMSE : 120, 0.11596662191371927
RMSE : 130, 0.10921017607773689
RMSE : 140, 0.1027238010078618
RMSE : 150, 0.09650991016689363
RMSE : 160, 0.09057009799692056
RMSE : 170, 0.08490487260170858
RMSE : 180, 0.07951350680993026
RMSE : 190, 0.07439398107382504
RMSE : 200, 0.06954299651141355
RMSE : 210, 0.06495604008810238
RMSE : 220, 0.06062748690900288
RMSE : 230, 0.056550727119732365
RMSE : 240, 0.0527183071320974
RMSE : 250, 0.049122076869351515
RMSE : 260, 0.04575333649027111
RMSE : 270, 0.042602977609287364
RMSE : 280, 0.03966161538230688
RMSE : 290, 0.03691970897671445
RMSE : 300, 0.03436766889586682
RMSE : 310, 0.0319959

In [ ]:
display(P)
display(Q)
display(np.dot(P, Q))

# array([[ 4., nan,  4.,  2.,  5.],
#        [nan,  4., nan,  1.,  2.],
#        [nan,  1.,  5.,  1., nan],
#        [ 1.,  5., nan, nan,  3.]])

array([[-0.46122928, -1.95753057, -0.80184156],
       [-0.17377654, -1.44807525,  1.13892805],
       [ 1.18781819, -1.68147511, -0.68764289],
       [ 1.75952316, -2.31584915,  1.39259294]])

array([[-0.2915459 , -0.35329319,  0.97808089, -0.44949672, -0.29801564],
       [-1.43728629, -1.48638993, -2.30245669, -0.81776767, -2.08977765],
       [-1.30344326,  1.55884927,  0.06835586, -0.23209351, -0.94637872]])

array([[3.99315633, 1.82265276, 4.00119925, 1.99422849, 4.98710295],
       [0.64743445, 3.98921569, 3.24201544, 0.99796331, 2.00008615],
       [2.96676108, 1.00774798, 4.98630147, 1.00073306, 3.8106913 ],
       [1.00039058, 4.99146981, 7.14829026, 0.77971491, 2.99732406]])